version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imcdb
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend/imc-api
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./frontend/imc-app:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - backend


